on:

  push:

    branches:

      - main

 

jobs:

  build:

    runs-on: ubuntu-latest

 

    steps:

    - name: Checkout code

      uses: actions/checkout@v2

 

    - name: Setup Terraform

      uses: hashicorp/setup-terraform@v1

 

    - name: Terraform Init

      run: terraform init

 

    - name: Terraform Validate

      run: terraform validate

 

    - name: Terraform Plan

      run: terraform plan

 

    - name: Terraform Apply

      run: terraform apply -auto-approve

 

    - name: Build and push Docker image

      uses: docker/build-push-action@v2

      with:

        context: .

        push: true

        tags: user/app:latest
